version: 2

jobs:

  tests:

    working_directory: ~/tests

    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm

    steps:
      - checkout

      - restore_cache:
            key: dependency-cache-test-v2-{{ checksum "package.json" }}

      - run:
          name: Node dependencies
          command: npm install

      - save_cache:
            key: dependency-cache-test-v2-{{ checksum "package.json" }}
            paths:
              - ./node_modules

      - run:
          name: Firebase Config
          command: npm run config:staging

      - run:
            name: Unit Tests
            command: npm run test:ci

      - run:
          name: Build
          command: npm run build

      - run:
          name: E2E tests
          command: npm run e2e:ci

  deploy:

    working_directory: ~/app/dist

    docker:
      - image: circleci/node:8
        environment:
          ## this enables colors in the output
          TERM: xterm

    steps:
      - checkout

      - restore_cache:
            key: dependency-cache-prod-v2-{{ checksum "package.json" }}

      - run:
          name: Node dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-prod-v2-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Firebase Config
          command: npm run config

      - run:
          name: Build
          command: npm run build -- --prod

      - run:
          name: Deploy
          command: npm run firebase -- deploy --token=$FIREBASE_TOKEN --project=$PROJECT_ID --non-interactive >/dev/null

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - tests
      - deploy:
          requires:
            - tests
          # Deploy only from master branch
          filters:
            branches:
              only: master
